#!/bin/bash

#"eval" function
foo=10 x=foo
y='$'$x
echo $x
echo $y
eval y='$'$x
echo $y

#"shift" function
echo $@
shift
echo $@

#read key/value pair
while read key val; do
    echo "$key"
    echo "$val"
    break
done

